name: Setup Micro-Manager Test Device Adapters

inputs:
  destination:
    description: Destination directory for the test device adapters.
    required: true
  version:
    description: Version of the test device adapters to install.
    required: false
    default: "latest"

runs:
  using: composite
  steps:
    - name: Get release version
      id: version
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          version=$(curl -s https://api.github.com/repos/pymmcore-plus/mm-test-adapters/releases/latest | jq -r .tag_name)
        else
          version="${{ inputs.version }}"
        fi

        echo "version=$version" >> $GITHUB_ENV
        echo "Using version: $version"

    - name: Download release file
      shell: bash
      run: |
        url="https://github.com/pymmcore-plus/mm-test-adapters/releases/download/$version/mm-test-adapters-${{ runner.os }}-${{ runner.arch }}.zip"
        echo "Downloading from: $url"
        curl -L -o mm-test-adapters.zip "$url"

    - name: Set Windows path
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # On Windows, use %LOCALAPPDATA%\pymmcore-plus\pymmcore-plus\mm
        echo "MM_DATA_DIR=${{ inputs.destination }}/pymmcore-plus/pymmcore-plus/mm" >> $GITHUB_ENV

    - name: Set macOS path
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # On macOS, use ~/Library/Application Support/pymmcore-plus/mm
        echo "MM_DATA_DIR=${{ inputs.destination }}/pymmcore-plus/mm" >> $GITHUB_ENV

    - name: Set Linux path
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # On Linux, use ~/.local/share/pymmcore-plus/mm
        echo "MM_DATA_DIR=${{ inputs.destination }}/pymmcore-plus/mm" >> $GITHUB_ENV

    - name: Extract files
      shell: bash
      run: |
        EXTRACT_DIR="$MM_DATA_DIR/Micro-Manager-${{ env.version }}"
        
        mkdir -p "$EXTRACT_DIR"
        unzip mm-test-adapters.zip -d "$EXTRACT_DIR"
        
        echo "Files extracted to: $EXTRACT_DIR"
        ls -la "$EXTRACT_DIR"
        rm mm-test-adapters.zip
