name: Setup Micro-Manager Test Device Adapters

description: >
  Downloads a specified or latest release of the pymmcore-plus test device adapters
  and extracts them into the given destination directory (or to sensible OS defaults).

inputs:
  destination:
    description: |
      (Optional) Destination directory for the test device adapters.
      If empty, defaults to:
        - Windows: %LOCALAPPDATA%\pymmcore-plus\pymmcore-plus\mm
        - macOS: ~/Library/Application Support/pymmcore-plus/mm
        - Linux: ~/.local/share/pymmcore-plus/mm
    required: false
    default: ""
  version:
    description: Version tag to install (or "latest")
    required: false
    default: "latest"

outputs:
  version:
    description: Resolved adapter version
    value: ${{ steps.get-version.outputs.version }}
  mm-data-dir:
    description: Directory where adapters were extracted
    value: ${{ steps.set-path.outputs.mm-data-dir }}

runs:
  using: composite
  steps:
    - name: Fetch release
      shell: bash
      id: download
      run: |
        # 1) figure out which tag to pull
        if [ "${{ inputs.version }}" = "latest" ]; then
          tag="latest"
        else
          tag="${{ inputs.version }}"
        fi

        # 2) download the matching asset in one go
        gh release download "$tag" \
          --repo pytmmcore-plus/mm-test-adapters \
          --pattern "mm-test-adapters-${{ runner.os }}-${{ runner.arch }}.zip" \
          --clobber \
          --dir .

        # gh will drop the file with its original name; rename for consistency
        mv "mm-test-adapters-${{ runner.os }}-${{ runner.arch }}.zip" mm-test-adapters.zip

        # record “version” for downstream steps/outputs
        echo "version=$tag" >> $GITHUB_ENV
        echo "version=$tag" >> $GITHUB_OUTPUT

    - name: Set MM_DATA_DIR
      shell: bash
      id: set-path
      run: |
        if [ -n "${{ inputs.destination }}" ]; then
          base="${{ inputs.destination }}"
        else
          case "${{ runner.os }}" in
            Windows) base="$LOCALAPPDATA/pymmcore-plus/pymmcore-plus/mm" ;;
            macOS)   base="$HOME/Library/Application Support/pymmcore-plus/mm" ;;
            Linux)   base="$HOME/.local/share/pymmcore-plus/mm" ;;
          esac
        fi

        # build final path and export only as a STEP OUTPUT
        mm_out="$base/Micro-Manager-$version"
        echo "mm-data-dir=$mm_out" >> $GITHUB_OUTPUT

    - name: Extract adapters
      shell: bash
      run: |
        out="${{ steps.set-path.outputs.mm-data-dir }}"
        mkdir -p "$out"
        unzip -o mm-test-adapters.zip -d "$out"
        rm mm-test-adapters.zip
