name: Test Action

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]

    steps:
      - uses: actions/checkout@v4
      - id: setup-mm
        uses: ./

      - name: Verify extraction
        run: |
          echo "▶ Using version: ${{ steps.setup-mm.outputs.version }}"
          echo "▶ Install path: ${{ steps.setup-mm.outputs.mm-data-dir }}"
          if [ ! -d "${{ steps.setup-mm.outputs.mm-data-dir }}" ]; then
            echo "❌ Extracted directory not found at $expected"
            exit 1
          fi
          echo "✅ Found $expected"
          echo "Contents of $expected:"
          ls -la "${{ steps.setup-mm.outputs.mm-data-dir }}"
