name: Test Setup Micro-Manager Test Device Adapters

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the action
        uses: ./  # This points to your local action
        with:
          destination: ./test-output
          version: latest
